#############################################################################
# Makefile for building: logclock
# Generated by qmake (2.01a) (Qt 4.6.3) on: ons. des. 5 20:55:31 2012
# Project:  logclock.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile logclock.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = logclock.cpp \
		main.cpp moc_logclock.cpp
OBJECTS       = logclock.o \
		main.o \
		moc_logclock.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		logclock.pro
QMAKE_TARGET  = logclock
DESTDIR       = 
TARGET        = logclock

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: logclock.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile logclock.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile logclock.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/logclock1.0.0 || $(MKDIR) .tmp/logclock1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/logclock1.0.0/ && $(COPY_FILE) --parents logclock.h .tmp/logclock1.0.0/ && $(COPY_FILE) --parents logclock.cpp main.cpp .tmp/logclock1.0.0/ && (cd `dirname .tmp/logclock1.0.0` && $(TAR) logclock1.0.0.tar logclock1.0.0 && $(COMPRESS) logclock1.0.0.tar) && $(MOVE) `dirname .tmp/logclock1.0.0`/logclock1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/logclock1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_logclock.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_logclock.cpp
moc_logclock.cpp: logclock.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) logclock.h -o moc_logclock.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

logclock.o: logclock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logclock.o logclock.cpp

main.o: main.cpp logclock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_logclock.o: moc_logclock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logclock.o moc_logclock.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./ || $(MKDIR) $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./ || $(MKDIR) $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./ 
	-$(INSTALL_FILE) /home/terjesc/prosjekter/logclock/logclock.cpp $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./
	-$(INSTALL_FILE) /home/terjesc/prosjekter/logclock/main.cpp $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./
	-$(INSTALL_FILE) /home/terjesc/prosjekter/logclock/logclock.h $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./
	-$(INSTALL_FILE) /home/terjesc/prosjekter/logclock/logclock.pro $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./logclock.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./logclock.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./logclock.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/home/terjesc/prosjekter/logclock/./ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

